#!/usr/bin/env php
<?php
const DICT_ALPHANUMERIC = "abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789";
const DICT_SYMBOLS = "@!#%*&+";

function generatePassword($length, $charset) {
	$retVal = "";
	$n = strlen($charset);

	for ($i = 0; $i < $length; ++$i) {
		$retVal .= substr($charset, rand(0, $n), 1);
	}

	return $retVal;
}

$length = $argv[1] ?? 12;
$useSymbols = boolval($argv[2] ?? 1);

$charset = DICT_ALPHANUMERIC;
if($useSymbols) $charset .= DICT_SYMBOLS;

$password = generatePassword($length, $charset);
$bcryptHash = password_hash($password, PASSWORD_BCRYPT);
$defaultHash = password_hash($password, PASSWORD_DEFAULT);

echo "\n";

echo "--------------\n";
echo "LQDI PASSWORD GENERATOR - V1.0\n";
echo "Usage: php passgen [<length=12> <useSymbols=1>]\n";
echo "--------------\n";

echo "\n\n";

echo "--------------\n";
echo "PASSWORD: \t\t {$password} \n";
echo "--------------\n";
echo "HASH_BCRYPT: \t\t {$bcryptHash} \n";
echo "HASH_DEFAULT: \t\t {$defaultHash} \n";
echo "--------------\n";
echo "\n\n";

exit();

